export type WebLanguage = "et" | "fi" | "en";

const messages = {
  et: { adminCenter: "Peakasutaja halduskeskus", email: "E-post", password: "Parool", codeHelp: "Sisestage e-postile saadetud 6-kohaline kinnituskood.", verificationCode: "Kinnituskood", testCode: "Testkood", back: "Tagasi", checking: "Kontrollin…", verifyEnter: "Kinnita ja sisene", continue: "Jätka", setPassword: "Määra uus parool", temporaryPassword: "Ajutine parool tuleb enne tööandmete avamist välja vahetada.", newPassword: "Uus parool", repeatPassword: "Uus parool uuesti", saving: "Salvestan…", changeContinue: "Muuda parool ja jätka", admin: "Peakasutaja", manager: "Meister / projektijuht", overview: "Ülevaade", presence: "Hetkel töömaal", clients: "Kliendid", workers: "Töötajad", managers: "Meistrid ja projektijuhid", sites: "Töömaad", corrections: "Parandustaotlused", reports: "Tööaja aruanded", invoices: "Arved", outbox: "Saatmisjärjekord", audit: "Auditilogi", logout: "Logi välja", helloAdmin: "Tere, peakasutaja", helloManager: "Tere, meister", sitesEntrances: "Töömaad ja sissepääsud", refreshData: "Uuenda andmeid", language: "Keel", activeClients: "Aktiivsed kliendid", currentlyOnSite: "Hetkel töömaal", totalInvoices: "Arveid kokku", overdue: "Tähtaja ületanud", queued: "Saatmisjärjekorras", pendingCorrections: "Ootel parandused", mySites: "Minu töömaad", workersInside: "Töötajaid sees", activeSites: "Aktiivseid töömaid", longShiftWarnings: "Pika vahetuse hoiatusi", currentlyRegistered: "Hetkel registreeritud", presenceHelp: "Andmed põhinevad viimasel IN/OUT registreeringul.", refresh: "Uuenda", nobodyOnSite: "Hetkel ei ole kedagi töömaale registreeritud", worker: "Töötaja", phone: "Telefon", site: "Töömaa", arrived: "Saabus", duration: "Kohapeal", status: "Olek", checkShift: "Kontrolli vahetust", onSite: "Töömaal", correctionTitle: "Tunnilehe parandustaotlused", correctionAuditHelp: "Algne QR-registreering jääb alati muutmata auditilogisse.", noCorrections: "Parandustaotlusi ei ole", date: "Kuupäev", requestedTime: "Soovitud aeg", reason: "Põhjus", actions: "Toimingud", pending: "Ootel", approved: "Kinnitatud", rejected: "Tagasi lükatud", approve: "Kinnita", reject: "Lükka tagasi", createReport: "Koosta tööaja aruanne", reportHelp: "Vali periood ja soovi korral üks töömaa.", start: "Algus", end: "Lõpp", allSites: "Kõik töömaad", showReport: "Näita aruannet", downloadCsv: "Laadi CSV", workdays: "Tööpäevad", rows: "rida", total: "kokku", hours: "tundi", choosePeriod: "Vali periood ja koosta aruanne", company: "Ettevõte", mark: "Märge", incomplete: "Pooleli", corrected: "Parandatud" },
  fi: { adminCenter: "Pääkäyttäjän hallintakeskus", email: "Sähköposti", password: "Salasana", codeHelp: "Syötä sähköpostiin lähetetty kuusinumeroinen vahvistuskoodi.", verificationCode: "Vahvistuskoodi", testCode: "Testikoodi", back: "Takaisin", checking: "Tarkistetaan…", verifyEnter: "Vahvista ja kirjaudu", continue: "Jatka", setPassword: "Aseta uusi salasana", temporaryPassword: "Väliaikainen salasana on vaihdettava ennen työtietojen avaamista.", newPassword: "Uusi salasana", repeatPassword: "Uusi salasana uudelleen", saving: "Tallennetaan…", changeContinue: "Vaihda salasana ja jatka", admin: "Pääkäyttäjä", manager: "Työnjohtaja / projektipäällikkö", overview: "Yleiskatsaus", presence: "Työmaalla nyt", clients: "Asiakkaat", workers: "Työntekijät", managers: "Työnjohtajat ja projektipäälliköt", sites: "Työmaat", corrections: "Korjauspyynnöt", reports: "Työaikaraportit", invoices: "Laskut", outbox: "Lähetysjono", audit: "Tarkastusloki", logout: "Kirjaudu ulos", helloAdmin: "Hei, pääkäyttäjä", helloManager: "Hei, työnjohtaja", sitesEntrances: "Työmaat ja sisäänkäynnit", refreshData: "Päivitä tiedot", language: "Kieli", activeClients: "Aktiiviset asiakkaat", currentlyOnSite: "Työmaalla nyt", totalInvoices: "Laskuja yhteensä", overdue: "Erääntyneet", queued: "Lähetysjonossa", pendingCorrections: "Odottavat korjaukset", mySites: "Omat työmaat", workersInside: "Työntekijöitä sisällä", activeSites: "Aktiiviset työmaat", longShiftWarnings: "Pitkän vuoron varoitukset", currentlyRegistered: "Tällä hetkellä kirjautuneet", presenceHelp: "Tiedot perustuvat viimeisimpään IN/OUT-kirjaukseen.", refresh: "Päivitä", nobodyOnSite: "Työmaalle ei ole tällä hetkellä kirjautuneita", worker: "Työntekijä", phone: "Puhelin", site: "Työmaa", arrived: "Saapui", duration: "Paikalla", status: "Tila", checkShift: "Tarkista vuoro", onSite: "Työmaalla", correctionTitle: "Työajan korjauspyynnöt", correctionAuditHelp: "Alkuperäinen QR-kirjaus säilyy aina muuttumattomana tarkastuslokissa.", noCorrections: "Korjauspyyntöjä ei ole", date: "Päivämäärä", requestedTime: "Toivottu aika", reason: "Perustelu", actions: "Toiminnot", pending: "Odottaa", approved: "Hyväksytty", rejected: "Hylätty", approve: "Hyväksy", reject: "Hylkää", createReport: "Luo työaikaraportti", reportHelp: "Valitse ajanjakso ja halutessasi yksi työmaa.", start: "Alku", end: "Loppu", allSites: "Kaikki työmaat", showReport: "Näytä raportti", downloadCsv: "Lataa CSV", workdays: "Työpäivät", rows: "riviä", total: "yhteensä", hours: "tuntia", choosePeriod: "Valitse ajanjakso ja luo raportti", company: "Yritys", mark: "Merkintä", incomplete: "Kesken", corrected: "Korjattu" },
  en: { adminCenter: "Administrator control centre", email: "Email", password: "Password", codeHelp: "Enter the six-digit verification code sent by email.", verificationCode: "Verification code", testCode: "Test code", back: "Back", checking: "Checking…", verifyEnter: "Verify and sign in", continue: "Continue", setPassword: "Set a new password", temporaryPassword: "The temporary password must be changed before opening work data.", newPassword: "New password", repeatPassword: "Repeat new password", saving: "Saving…", changeContinue: "Change password and continue", admin: "Administrator", manager: "Site manager / project manager", overview: "Overview", presence: "Currently on site", clients: "Clients", workers: "Workers", managers: "Site and project managers", sites: "Sites", corrections: "Correction requests", reports: "Timesheet reports", invoices: "Invoices", outbox: "Send queue", audit: "Audit log", logout: "Log out", helloAdmin: "Hello, administrator", helloManager: "Hello, site manager", sitesEntrances: "Sites and entrances", refreshData: "Refresh data", language: "Language", activeClients: "Active clients", currentlyOnSite: "Currently on site", totalInvoices: "Total invoices", overdue: "Overdue", queued: "In send queue", pendingCorrections: "Pending corrections", mySites: "My sites", workersInside: "Workers inside", activeSites: "Active sites", longShiftWarnings: "Long-shift warnings", currentlyRegistered: "Currently registered", presenceHelp: "Data is based on the latest IN/OUT registration.", refresh: "Refresh", nobodyOnSite: "Nobody is currently registered on site", worker: "Worker", phone: "Phone", site: "Site", arrived: "Arrived", duration: "On site", status: "Status", checkShift: "Check shift", onSite: "On site", correctionTitle: "Timesheet correction requests", correctionAuditHelp: "The original QR registration always remains unchanged in the audit log.", noCorrections: "No correction requests", date: "Date", requestedTime: "Requested time", reason: "Reason", actions: "Actions", pending: "Pending", approved: "Approved", rejected: "Rejected", approve: "Approve", reject: "Reject", createReport: "Create timesheet report", reportHelp: "Select a period and optionally one site.", start: "Start", end: "End", allSites: "All sites", showReport: "Show report", downloadCsv: "Download CSV", workdays: "Workdays", rows: "rows", total: "total", hours: "hours", choosePeriod: "Select a period and create a report", company: "Company", mark: "Note", incomplete: "In progress", corrected: "Corrected" },
} as const;

export type WebTranslationKey = keyof typeof messages.et;
export function webTranslate(language: WebLanguage, key: WebTranslationKey) { return messages[language][key]; }
export function initialWebLanguage(): WebLanguage {
  const stored = localStorage.getItem("siteclock.web-language.v1");
  return stored === "fi" || stored === "en" ? stored : "et";
}
export function persistWebLanguage(language: WebLanguage) {
  localStorage.setItem("siteclock.web-language.v1", language);
  document.documentElement.lang = language;
}

const operationalText: Record<Exclude<WebLanguage, "et">, Record<string, string>> = {
  fi: { "Lisa töötaja": "Lisää työntekijä", "Töötaja seotakse veebirakenduses oleva ettevõtte ja töömaaga": "Työntekijä yhdistetään verkkopalvelussa yritykseen ja työmaahan", "Klient": "Asiakas", "Vali klient": "Valitse asiakas", "Nimi": "Nimi", "Amet": "Tehtävä", "Kõik töömaad": "Kaikki työmaat", "Salvestan…": "Tallennetaan…", "kasutajat": "käyttäjää", "Kõik": "Kaikki", "Aktiivne": "Aktiivinen", "Peatatud": "Keskeytetty", "Peata": "Keskeytä", "Aktiveeri": "Aktivoi", "Lähtesta PIN": "Nollaa PIN", "Ekspordi andmed": "Vie tiedot", "Anonümiseeri": "Anonymisoi", "Lisa töömaa": "Lisää työmaa", "Asukohta kasutatakse QR-registreeringu kontrollimiseks": "Sijaintia käytetään QR-kirjauksen tarkistamiseen", "Töömaa nimi": "Työmaan nimi", "Aadress": "Osoite", "Laiuskraad": "Leveysaste", "Pikkuskraad": "Pituusaste", "Lubatud raadius (m)": "Sallittu säde (m)", "Loo töömaa": "Luo työmaa", "Töömaid pole veel loodud": "Työmaita ei ole vielä luotu", "Aadress puudub": "Osoite puuttuu", "raadius": "säde", "Kohalolijate PDF": "Läsnäolijoiden PDF", "Sissepääsud": "Sisäänkäynnit", "Sissepääse pole lisatud.": "Sisäänkäyntejä ei ole lisätty.", "Ava QR-leht": "Avaa QR-arkki", "Uuenda koodid": "Päivitä koodit", "Sissepääsu nimi": "Sisäänkäynnin nimi", "Lisa sissepääs": "Lisää sisäänkäynti", "Ettevõte": "Yritys", "Olek": "Tila", "Toimingud": "Toiminnot" },
  en: { "Lisa töötaja": "Add worker", "Töötaja seotakse veebirakenduses oleva ettevõtte ja töömaaga": "The worker is linked to a company and site in the web application", "Klient": "Client", "Vali klient": "Select client", "Nimi": "Name", "Amet": "Job title", "Kõik töömaad": "All sites", "Salvestan…": "Saving…", "kasutajat": "users", "Kõik": "All", "Aktiivne": "Active", "Peatatud": "Suspended", "Peata": "Suspend", "Aktiveeri": "Activate", "Lähtesta PIN": "Reset PIN", "Ekspordi andmed": "Export data", "Anonümiseeri": "Anonymise", "Lisa töömaa": "Add site", "Asukohta kasutatakse QR-registreeringu kontrollimiseks": "The location is used to verify QR registrations", "Töömaa nimi": "Site name", "Aadress": "Address", "Laiuskraad": "Latitude", "Pikkuskraad": "Longitude", "Lubatud raadius (m)": "Allowed radius (m)", "Loo töömaa": "Create site", "Töömaid pole veel loodud": "No sites have been created yet", "Aadress puudub": "Address missing", "raadius": "radius", "Kohalolijate PDF": "Presence PDF", "Sissepääsud": "Entrances", "Sissepääse pole lisatud.": "No entrances have been added.", "Ava QR-leht": "Open QR sheet", "Uuenda koodid": "Refresh codes", "Sissepääsu nimi": "Entrance name", "Lisa sissepääs": "Add entrance", "Ettevõte": "Company", "Olek": "Status", "Toimingud": "Actions" },
};

export function webUiText(language: WebLanguage, estonian: string) {
  return language === "et" ? estonian : operationalText[language][estonian] ?? estonian;
}

const accountText: Record<Exclude<WebLanguage, "et">, Record<string, string>> = {
  fi: { "Muuda klienti": "Muokkaa asiakasta", "Lisa klient": "Lisää asiakas", "Arvelduse põhiseaded": "Laskutuksen perusasetukset", "Tühista muutmine": "Peruuta muokkaus", "Ettevõtte nimi": "Yrityksen nimi", "Registrikood": "Y-tunnus", "Arve e-post": "Laskutuksen sähköposti", "Kuutasu ilma KM-ta": "Kuukausimaksu ilman ALV:tä", "Saada arved automaatselt": "Lähetä laskut automaattisesti", "Salvesta muudatused": "Tallenna muutokset", "Salvesta klient": "Tallenna asiakas", "Arvelduse ja automaatse saatmise seaded": "Laskutuksen ja automaattisen lähetyksen asetukset", "Kuutasu": "Kuukausimaksu", "Saatmine": "Lähetys", "Konto olek": "Tilin tila", "Automaatne": "Automaattinen", "Kinnitusega": "Vahvistettava", "Piiratud kasutus": "Rajoitettu käyttö", "Maksehoiatus": "Maksuvaroitus", "Käsitsi peatatud": "Keskeytetty manuaalisesti", "Muuda": "Muokkaa", "Piira": "Rajoita", "Taasta": "Palauta", "Lisa meister või projektijuht": "Lisää työnjohtaja tai projektipäällikkö", "Konto näeb ainult valitud kliendi tööandmeid.": "Tili näkee vain valitun asiakkaan työtiedot.", "Rollinimetus": "Rooli", "Meister": "Työnjohtaja", "Projektijuht": "Projektipäällikkö", "Esialgne parool": "Alustava salasana", "Loo kasutajakonto": "Luo käyttäjätili", "Kasutajakontod": "Käyttäjätilit", "meistrit või projektijuhti": "työnjohtajaa tai projektipäällikköä", "Roll": "Rooli", "Peata konto": "Keskeytä tili", "Lähtesta parool": "Nollaa salasana" },
  en: { "Muuda klienti": "Edit client", "Lisa klient": "Add client", "Arvelduse põhiseaded": "Basic billing settings", "Tühista muutmine": "Cancel editing", "Ettevõtte nimi": "Company name", "Registrikood": "Registry code", "Arve e-post": "Billing email", "Kuutasu ilma KM-ta": "Monthly fee excluding VAT", "Saada arved automaatselt": "Send invoices automatically", "Salvesta muudatused": "Save changes", "Salvesta klient": "Save client", "Arvelduse ja automaatse saatmise seaded": "Billing and automatic sending settings", "Kuutasu": "Monthly fee", "Saatmine": "Sending", "Konto olek": "Account status", "Automaatne": "Automatic", "Kinnitusega": "With confirmation", "Piiratud kasutus": "Restricted access", "Maksehoiatus": "Payment warning", "Käsitsi peatatud": "Manually suspended", "Muuda": "Edit", "Piira": "Restrict", "Taasta": "Restore", "Lisa meister või projektijuht": "Add site or project manager", "Konto näeb ainult valitud kliendi tööandmeid.": "The account can only see the selected client's work data.", "Rollinimetus": "Role title", "Meister": "Site manager", "Projektijuht": "Project manager", "Esialgne parool": "Initial password", "Loo kasutajakonto": "Create user account", "Kasutajakontod": "User accounts", "meistrit või projektijuhti": "site or project managers", "Roll": "Role", "Peata konto": "Suspend account", "Lähtesta parool": "Reset password" },
};

export function webAccountText(language: WebLanguage, estonian: string) {
  return language === "et" ? estonian : accountText[language][estonian] ?? estonian;
}
